### ISSUE TITLE
Update node module ?

### ISSUE THREAD

**Issue by jeremio** [ryaninvents/positive-outlook#2]
I would like to use this module but I wonder if there will be an update with dependencies. I encountered callback problems like this : 
https://github.com/SamDecrock/node-http-ntlm/commit/f3110c6f977f9e195543313c93d1c9f3f39806b7

**Comment by ryaninvents** [comment]
Thanks for your feedback. Looks like I need to change `"httpntlm-3": "^1.5.2"` to `"httpntlm": "^1.7.2"`.

In the meantime, I might recommend you try [`ews-javascript-api`](https://www.npmjs.com/package/ews-javascript-api) instead, as it's a mature and well-maintained project. I'd like to update this package, but it may be pragmatic for you to use the other one in terms of completeness and stability. In the future I may either reimplement this package on top of that one, or deprecate `positive-outlook` in favor of `ews-javascript-api`.

**Comment by jeremio** [comment]
No problem, it's a pleasure to update this node module. I am new node developer.

I try to use "httpntlm": "^1.7.2". That's not work.  
"soap-3": "^0.11.3" uses httplm-3 and i have this error : " Error: www-authenticate not found on response of second request
    at /positive-outlook/node_modules/httpntlm-3/httpntlm.js:62:14"

Then, i change soap-3 to "soap": "^0.23.0" and i have this message : 
TypeError: _soap2.default.NtlmSecurity is not a constructor
    at _callee$ (/positive-outlook/src/index.js:117:26) on this line :       
client.setSecurity(new soap.NtlmSecurity(soapOptions.wsdl_options));

I would like get messages' user from old version of Microsoft Exchange
I will see ews-javascript-api too, thanks

**Comment by ryaninvents** [comment]
> I am new node developer.

Welcome to the community! 🎉 

Since you're new to JS, I'm going to go ahead and say: if this package confuses you, blame the package author and not yourself 😂 I was experimenting with an API, and ultimately the experiment did not work out.

> TypeError: _soap2.default.NtlmSecurity is not a constructor

Ah yes, I'm just now remembering the dependency nightmare that's in this project 😕 Thanks for your help in debugging, I'll see if I can make some changes soon.
